name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull saurabh98019/react-cicd:latest
    - name: Delete Old docker container
      run: sudo docker rm -f react-cicd-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 80:80 --name react-cicd-container saurabh98019/react-cicd
